$(function(){$("textarea[maxlength]").keyup(function(){var area=$(this);var max=parseInt(area.attr("maxlength"),200);if(max>0){if(area.val().length>max){area.val(area.val().substr(0,max));}}});$('input[placeholder], textarea[placeholder]').placeholder();String.prototype.longlength=function(){return this.replace(/[^\x00-\xff]/g,"**").length;}
$('#top').on('click','a.topLogin',function(){JqueryDialog.Open($(this).attr('title'),$(this).attr('href'),460,295);return false;});$('#top').on('click','a.topMessage',function(){JqueryDialog.Open1($(this).attr('title'),$(this).attr('href'),880,560,false,false,true);return false;});$('a.sendMessage').on('click',function(){JqueryDialog.Open1($(this).attr('title'),$(this).attr('href'),880,560,false,false,true);return false;});$('#top').on('click','a.topLogout',function(){if(confirm('确定要退出吗?')){$.post($(this).attr('href'),function(data){if(data=='success'){window.location.reload();}
else{alert(data);}});}
return false;});$('#t_feedback').click(function(){JqueryDialog.Open1($(this).attr('title'),$(this).attr('href'),600,350,false,false,true);return false;});weixin();$('#t_gotop').click(function(){$(document).scrollTop(0);});$('#t_code').hover(function(){$(this).attr('id','t_code_hover');$('#t_code_img').show();},function(){$(this).attr('id','t_code');$('#t_code_img').hide();});});$(window).scroll(function(e){weixin();});function weixin(){h=$(window).height()-100;t=$(document).scrollTop();if(t>h){$('#t_gotop').show();}else{$('#t_gotop').hide();}}
function mfs(){var mfs=[];$('img').each(function(){if($(this).attr('src').indexOf('http://www.ipathology.org.cn')>-1){mfs.push($(this).attr('src'));}});if(mfs.length>0){var mfs_str=mfs.join(";");$.ajax({url:"/mfs/info",type:"POST",data:{mfs:mfs_str},dataType:'html',async:false,success:function(data){}});}}
function ascii(str){return str.replace(/[^\u0000-\u00FF]/g,function($0){return escape($0).replace(/(%u)(\w{4})/gi,"\&#x$2;")});}
function getCity(pid,city){$.ajax({url:"/ajax/area",type:"POST",data:"pid="+pid+"&t="+ Math.random(),dataType:'html',async:false,success:function(data){$('#'+city).html(data);}});}
function addTips(id,tips){var controlGroup=$('#'+id+'-help').parents('.control-group');if(''==tips){controlGroup.removeClass('error');$('#'+id+'-help').text('');}else{controlGroup.addClass('error');$('#'+id+'-help').text(tips);}}
function delLoading(self,classname){if(typeof(classname)=="undefined"){classname='icon-remove';}
$(self).children('i').removeClass(classname);$(self).children('i').addClass('loading-icon');}
function resetDelLoading(self,classname){if(typeof(classname)=="undefined"){classname='icon-remove';}
$(self).children('i').removeClass('loading-icon');$(self).children('i').addClass(classname);}
function loginState(curUrl){$.ajax({url:"/login/state",type:"POST",data:{curUrl:curUrl,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.user-login-state').html(data.content);return false;}}});}
function getNotice(){$.get('/notice.html',{rand:Math.random()},function(data){$('#noticecount').text(parseInt(data));setTimeout("getNotice()",91000);});}
function getMessage(){$.get('/message.html',{rand:Math.random()},function(data){if(data!='登录'){$('#msgcount').text(parseInt(data));setTimeout("getMessage()",59000);}else{alert("您的登录状态已失效，或者在其它地方登录，请重新登录！");window.location.reload();}});}
function getVisit(module,type,limit){$.ajax({url:"/visit/get",type:"POST",data:{module:module,type:type,limit:limit,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.reader').show();$('.reader-loading').hide();$('.reader').html(data.content);}}});}
function sendVisit(rid,module){$.post("/visit/send",{rid:rid,module:module,t:Math.random()});}
function getRelative(rid,module,divname,isremove,limit,pointer){if(typeof(isremove)=="undefined")
isremove=true;if(typeof(limit)=="undefined")
limit=5;if(typeof(pointer)=="undefined")
pointer=pointer;$.ajax({url:"/relative",type:"POST",data:{module:module,rid:rid,limit:limit,pointer:pointer,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.'+divname+'>ul').html(data.content);}else{if(isremove==true){$('.'+divname).remove();}else{$('.'+divname+'>ul').html('<li>暂无相关资源</li>');}}}});}
function getComment(rid,module,page,submodule,infotype){submodule=submodule||'';infotype=infotype||'';$.ajax({url:"/comment/get",type:"POST",data:{rid:rid,module:module,page:page,submodule:submodule,infotype:infotype,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.div-comment-list>ul').append(data.content);$('.btn-comment-more').remove();if(''!=data.page){$('.div-comment-list').append(data.page)}
$('.count-comment-all').text(data.count);return false;}}});}
function getComment2(rid,module,page,submodule,infotype){submodule=submodule||'';infotype=infotype||'';$.ajax({url:"/comment/get",type:"POST",data:{rid:rid,module:module,page:page,submodule:submodule,infotype:infotype,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.div-comment-list>ul').html(data.content);$('.btn-comment-more').remove();if(''!=data.page){$('.div-comment-list').append(data.page)}
$('.count-comment-all').text(data.count);return false;}}});}
function loginComment(curUrl){$.ajax({url:"/comment/login",type:"POST",data:{curUrl:curUrl,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.div-comment-form').html(data.content);return false;}}});}
function postComment(rid,content,module,submodule,infotype){submodule=submodule||'';infotype=infotype||'';$('.btn-comment').attr('disabled','disabled');$.ajax({url:"/comment/post",type:"POST",data:{rid:rid,content:content,module:module,submodule:submodule,infotype:infotype,t:Math.random()},dataType:'json',success:function(data){$('.btn-comment').attr('disabled',false);if('ok'==data.status){$('.div-comment-list>ul').prepend(data.content);$('#content-comment').val('');return false;}else{alert(data.content);return false;}}});}
function revertComment(parentid,module,submodule,infotype){submodule=submodule||'';infotype=infotype||''
var content=$.trim($('.reply_box_'+parentid).val());if(''==content){alert('请输入回复内容');$('.reply_box_'+parentid).focus();return false;}
$.ajax({url:"/comment/revert",type:"POST",data:{parentid:parentid,content:content,module:module,submodule:submodule,infotype:infotype,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.reply_reply_'+parentid).parent().find('.btn-show-reply').text(data.count);$('.reply_child_'+parentid).prepend(data.content);$('.reply_box_'+parentid).val('');$('.reply_box_'+parentid).parent().hide();return false;}else{alert(data.content);return false;}}});}
function getCommentTop(module,submodule){submodule=submodule||'';$.ajax({url:"/comment/top",type:"POST",data:{module:module,submodule:submodule,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$('.comment_top').html(data.content);return false;}}});}
function pollComment(self,rid,opt){$.ajax({url:"/comment/poll",type:"POST",data:{rid:rid,opt:opt,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){$(self).text(data.tips);return false;}else{alert(data.content);return false;}}});}
function showRevertComment(rid){var curUrl=window.location.href;$.ajax({url:"/comment/login",type:"POST",data:{curUrl:curUrl,t:Math.random()},dataType:'json',success:function(data){if(''!=data.login){if(confirm('请先登录，再回复！\n确认登录吗')){window.location.href=data.login;return false;}}}});if($('.reply_reply_'+rid).is(":hidden")){$('.reply_reply_'+rid).show();}else{$('.reply_reply_'+rid).hide();}}
function getFavourite(rid,module,flag){$.ajax({url:"/favorite",type:"POST",data:{rid:rid,module:module,flag:flag,t:Math.random()},dataType:'json',success:function(data){if('ok'==data.status){if($(".rownum_"+rid).length==0){$('.favorite-load').html(data.content);}else{$(".rownum_"+rid).html(data.content);}
var r=$('.favorite-load').data('flag');if(r=='1'&&flag!=1){var tips=data.r==true?'收藏成功':'取消成功';easyDialog.open({container:{content:"<p class='text-center' style='margin:0;'>"+tips+"</p>",width:150},autoClose:2000,overlay:false});}
return false;}else{alert(data.content);return false;}}});}
function keyup(num,source,show){var infos=document.getElementById(show);curlen=source.value.longlength();last=num-curlen;if(last<=0){source.value=source.value.substring(0,num);last=0;}
infos.innerHTML=last;}
function gradePoll(domid,rid,module){var $star=$('#'+domid);$star.raty({click:function(){var score=$star.raty('score');$.ajax({url:'/grade/poll',type:'POST',data:{score:score,module:module,rid:rid},cache:false,dataType:'json',success:function(result){if('ok'==result.status){$star.raty('readOnly',true);}else{alert(result.msg);}}})}});}
function ajax_jumpto(){var page=$.trim($('#hd_page').val());var r=/^\+?[1-9][0-9]*$/;if(!r.test(page)){alert('您好，请输入正确页码。');return false;}
var url=$.trim($('#hd_url').val());var pageurl=$.trim($('#hd_pageurl').val());var params=$.trim($('#hd_params').val());$.ajax({url:'/jumpto.html',type:'POST',data:{page:page,url:url,pageurl:pageurl,params:params,t:Math.random()},cache:false,dataType:'json',success:function(result){if('ok'==result.status){window.location.href=result.url;return true;}else{alert('操作异常！');return false;}}})}
function change_state_url(self,fid,fieldname,tablename,url){var isopen=$(self).hasClass('state-open');if(typeof(url)=='undefined'){url="/api/state";}
$(self).removeClass('state-open');$(self).removeClass('state-close');$(self).addClass('state-load');$.ajax({url:url,type:"post",data:{fid:fid,fieldname:fieldname,tablename:tablename,t:Math.random()},dataType:'json',success:function(data){$(self).removeClass('state-load');if('error'==data.status){if(isopen){$(self).addClass('state-open');}else{$(self).addClass('state-close');}
alert(data.msg);return false;}else{if(1==data.msg){$(self).addClass('state-open');}else{$(self).addClass('state-close');}
return false;}}});}
function change_delete_url(self,fid,fieldname,tablename,url){var modulename=modulename||'';var fid=$(self).data('id');var title=$(self).data('title');if(typeof(url)=='undefined'){alert('操作异常');return false;}
easyDialog.open({container:{header:'删除信息',content:'您确认删除【'+title+'】吗？注意删除后不可以恢复！',yesFn:function(){delLoading(self);$.ajax({url:url,type:"POST",data:{fid:fid,fieldname:fieldname,tablename:tablename,t:Math.random()},dataType:'json',async:false,success:function(data){resetDelLoading(self);if('ok'!=data.status){easyDialog.close();alert(data.msg);return false;}
$('.tr_'+fid).animate({opacity:"hide"},"slow");return false;}});},noFn:true}});}
var only_toolbar=[['bold','italic','underline','|','paragraph','fontsize','|','forecolor','backcolor','|','insertorderedlist','insertunorderedlist','|','justifyleft','justifycenter','justifyright','justifyjustify','|','link','unlink','|','inserttable','deletetable','|','source']];var mini_toolbar=[['source','|','undo','redo','|','bold','italic','underline','fontborder','strikethrough','superscript','subscript','removeformat','formatmatch','autotypeset','blockquote','pasteplain','|','forecolor','backcolor','insertorderedlist','insertunorderedlist','selectall','cleardoc','|','rowspacingtop','rowspacingbottom','lineheight','|','customstyle','paragraph','fontfamily','fontsize','|','directionalityltr','directionalityrtl','indent','|','justifyleft','justifycenter','justifyright','justifyjustify','|','touppercase','tolowercase','|','link','unlink','anchor','|','imagenone','imageleft','imageright','imagecenter','|','insertimage','emotion','insertframe','template','|','horizontal','spechars','wordimage','|','inserttable','deletetable','insertparagraphbeforetable','insertrow','deleterow','insertcol','deletecol','mergecells','mergeright','mergedown','splittocells','splittorows','splittocols','charts']];var bd_toolbar=[['fullscreen','source','|','undo','redo','|','bold','italic','underline','fontborder','strikethrough','superscript','subscript','removeformat','formatmatch','autotypeset','blockquote','pasteplain','|','forecolor','backcolor','insertorderedlist','insertunorderedlist','selectall','cleardoc','|','rowspacingtop','rowspacingbottom','lineheight','|','customstyle','paragraph','fontfamily','fontsize','|','directionalityltr','directionalityrtl','indent','|','justifyleft','justifycenter','justifyright','justifyjustify','|','touppercase','tolowercase','|','link','unlink','anchor','|','imagenone','imageleft','imageright','imagecenter','|','insertimage','emotion','insertframe','template','|','horizontal','spechars','wordimage','|','inserttable','deletetable','insertparagraphbeforetable','insertrow','deleterow','insertcol','deletecol','mergecells','mergeright','mergedown','splittocells','splittorows','splittocols','charts']];