var JqueryDialog={"cBorderSize":0,"refreshFrame":null,"cSubmitText":"确认","cCancelText":"取消","cDragTime":"100","storeWidth":0,"storeHeight":0,"storeLeft":0,"storeTop":0,"bottomButton":true,"t_w_ie6":($.browser.msie&&($.browser.version=="6.0")&&!$.support.style)?122:4,Open:function(dialogTitle,iframeSrc,iframeWidth,iframeHeight){JqueryDialog.init(dialogTitle,iframeSrc,iframeWidth,iframeHeight,true,true,true,'',true);},Open1:function(dialogTitle,iframeSrc,iframeWidth,iframeHeight,isSubmitButton,isCancelButton,isDrag){JqueryDialog.init(dialogTitle,iframeSrc,iframeWidth,iframeHeight,isSubmitButton,isCancelButton,isDrag,'',true);},Open2:function(dialogTitle,diaglogText,dialogWidth,dialogHeight,operateFun){JqueryDialog.Ok=operateFun;JqueryDialog.init(dialogTitle,'',dialogWidth,dialogHeight,true,true,true,diaglogText,false);},Open3:function(dialogTitle,iframeSrc,iframeWidth,iframeHeight,isSubmitButton,isCancelButton,isDrag){JqueryDialog.init(dialogTitle,iframeSrc,iframeWidth,iframeHeight,isSubmitButton,isCancelButton,isDrag,'',true);},Dialog:function(diaglogText,dialogTitle,dialogWidth,dialogHeight,closeTime,closeFun){diaglogText='<div class="tip_dialog"><i class="success"></i>'+diaglogText+'</div>';JqueryDialog.init(dialogTitle,'',dialogWidth,dialogHeight,false,false,true,diaglogText,false);setTimeout("JqueryDialog.Close();"+closeFun,closeTime*1000);},init:function(dialogTitle,iframeSrc,iframeWidth,iframeHeight,isSubmitButton,isCancelButton,isDrag,diaglogText,isChangeSize){if($('#jd_dialog').length>0){$("#jd_shadow").show();$('#jd_dialog').show();return true;}
var _client_width=document.body.clientWidth;var _client_height=document.documentElement.scrollHeight;JqueryDialog.storeWidth=iframeWidth;JqueryDialog.storeHeight=iframeHeight;if(typeof($("#jd_shadow")[0])=="undefined"){$("body").append("<div id='jd_shadow'>&nbsp;</div>");var _jd_shadow=$("#jd_shadow");_jd_shadow.css("width",_client_width+"px");_jd_shadow.css("height",_client_height+"px");}
if(typeof($("#jd_dialog")[0])!="undefined"){$("#jd_dialog").remove();}
$("body").append("<div id='jd_dialog'></div>");var _jd_dialog=$("#jd_dialog");var _left=(_client_width- iframeWidth)/ 2;
JqueryDialog.storeLeft=(_left<0?0:_left)+ document.documentElement.scrollLeft;_jd_dialog.css("left",JqueryDialog.storeLeft+"px");var _top=(document.documentElement.clientHeight-(iframeHeight+ 20))/ 2;
JqueryDialog.storeTop=(_top<0?0:_top)+(window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop);_jd_dialog.css("top",JqueryDialog.storeTop+"px");_jd_dialog.append("<div id='jd_dialog_m'></div>");var _jd_dialog_m=$("#jd_dialog_m");_jd_dialog_m.css("width",iframeWidth+"px");_jd_dialog_m.append("<div id='jd_dialog_m_h2' class='layer_global_title clearfix'></div>");var _jd_dialog_m_h=$("#jd_dialog_m_h2");if(''!=dialogTitle){_jd_dialog_m_h.append("<span id='jd_dialog_m_h2_l' class='pull-left'><b>"+ dialogTitle+"</b></span>");}
_jd_dialog_m_h.append("<span id='jd_dialog_m_h2_r' class='pull-right'>"+(isChangeSize?"<button class='maxsize' title='最大化' onclick='JqueryDialog.Maxsize();'><button class='ressize' title='还原' onclick='JqueryDialog.Ressize();' style='display:none;'></button>":"<div class='blank'></div>")+"<button class='closewin' title='关闭' onclick='JqueryDialog.Close(false);'></button></span>");_jd_dialog_m.append("<div id='jd_dialog_m_b'></div>");var _jd_dialog_m_b=$("#jd_dialog_m_b");_jd_dialog_m_b.css("width",iframeWidth+"px");_jd_dialog_m_b.css("height",iframeHeight+"px");_jd_dialog_m_b.append("<div id='jd_dialog_m_b_1'></div>");var _jd_dialog_m_b_1=$("#jd_dialog_m_b_1");_jd_dialog_m_b_1.css("top","32px");_jd_dialog_m_b_1.css("width",iframeWidth+"px");_jd_dialog_m_b_1.css("height",iframeHeight+"px");_jd_dialog_m_b_1.css("display","none");_jd_dialog_m_b.append("<div id='jd_dialog_m_b_2'></div>");if(iframeSrc!=''){$("#jd_dialog_m_b_2").append("<iframe id='jd_iframe' src='"+iframeSrc+"' scrolling='no' frameborder='0' width='"+iframeWidth+"' height='"+iframeHeight+"' />");}
else{$("#jd_dialog_m_b_2").append(diaglogText);}
if((isSubmitButton||isCancelButton)&&JqueryDialog.bottomButton){_jd_dialog_m.append("<div id='jd_dialog_m_t' style='width:"+(iframeWidth- 2)+"px;'></div>");var _jd_dialog_m_t=$("#jd_dialog_m_t");if(isSubmitButton){_jd_dialog_m_t.append("<button id='jd_submit' onclick='JqueryDialog.Ok();'>"+JqueryDialog.cSubmitText+"</button>");}
if(isCancelButton){_jd_dialog_m_t.append("<button id='jd_cancel' onclick='JqueryDialog.Close(true);'>"+JqueryDialog.cCancelText+"</button>");}}
_jd_dialog_m.append("<div id='jd_dialog_b'><span id='jd_dialog_b_l'></span><span id='jd_dialog_b_m' style='width:"+(iframeWidth- 4)+"px;'></span><span id='jd_dialog_b_r'></span></div>");if(isDrag){DragAndDrop.Register($("#jd_dialog"),$("#jd_dialog_m_h2"));}},Close:function(cancel){$("#jd_dialog_m_b_1").remove();$("#jd_dialog_m_b").remove();$("#jd_shadow").remove();$("#jd_dialog").remove();if(JqueryDialog.refreshFrame!=null&&!cancel){JqueryDialog.refreshFrame.location.reload();}},Maxsize:function(cancel){$('#jd_dialog').css({"left":document.documentElement.scrollLeft+"px","top":document.documentElement.scrollTop+"px"});$("#jd_dialog_m").css("width",document.body.clientWidth+"px");$("#jd_dialog_m_b").css({"width":($(window).width())+"px","height":($(window).height()- 33- $('#jd_dialog_m_t').height())+"px"});$("#jd_iframe").css({"width":($(window).width())+"px","height":($(window).height()- 33- $('#jd_dialog_m_t').height())+"px"});$("#jd_dialog_m_h_m").css("width",($(window).width()- JqueryDialog.t_w_ie6)+"px");$("#jd_dialog_m_t").css("width",($(window).width())+"px");$("#jd_dialog_b_m").css("width",($(window).width())+"px");$('button.maxsize').hide();$('button.ressize').show();},Ressize:function(cancel){$('#jd_dialog').css({"left":JqueryDialog.storeLeft+"px","top":JqueryDialog.storeTop+"px"});$("#jd_dialog_m").css("width",JqueryDialog.storeWidth+"px");$("#jd_dialog_m_b").css({"width":(JqueryDialog.storeWidth)+"px","height":JqueryDialog.storeHeight+"px"});$("#jd_iframe").css({"width":(JqueryDialog.storeWidth)+"px","height":JqueryDialog.storeHeight+"px"});$("#jd_dialog_m_h_m").css("width",(JqueryDialog.storeWidth- JqueryDialog.t_w_ie6)+"px");$("#jd_dialog_m_t").css("width",(JqueryDialog.storeWidth)+"px");$("#jd_dialog_b_m").css("width",(JqueryDialog.storeWidth)+"px");$('button.ressize').hide();$('button.maxsize').show();},Minsize:function(cancel){$('#jd_dialog').hide();$("#jd_shadow").hide();},Ok:function(){var frm=$("#jd_iframe");if(frm[0].contentWindow.Ok()){JqueryDialog.Close(false);}
else{frm[0].focus();}},SubmitCompleted:function(alertMsg,isCloseDialog,isRefreshPage){if(isCloseDialog){JqueryDialog.Close(false);if(isRefreshPage){window.location.reload();}
if(alertMsg!=''){try
{if(typeof(eval(alertMsg))=="function")
{eval(alertMsg)();}
else{alert(alertMsg);}}catch(e)
{alert(alertMsg);}}}}};var DragAndDrop=function(){var _clientWidth;var _clientHeight;var _controlObj;var _dragObj;var _flag=false;var _dragObjCurrentLocation;var _mouseLastLocation;var _timer;var intervalMove=function(){$(_dragObj).css("left",_dragObjCurrentLocation.x+"px");$(_dragObj).css("top",_dragObjCurrentLocation.y+"px");};var getElementDocument=function(element){return element.ownerDocument||element.document;};var dragMouseDownHandler=function(evt){if(_dragObj){evt=evt||window.event;_clientWidth=document.body.clientWidth;_clientHeight=document.documentElement.scrollHeight;$("#jd_dialog_m_b_1").show();_flag=true;_dragObjCurrentLocation={x:$(_dragObj).offset().left,y:$(_dragObj).offset().top};_mouseLastLocation={x:evt.screenX,y:evt.screenY};$(document).bind("mousemove",dragMouseMoveHandler);$(document).bind("mouseup",dragMouseUpHandler);if(evt.preventDefault)
evt.preventDefault();else
evt.returnValue=false;}};var dragMouseMoveHandler=function(evt){if(_flag){evt=evt||window.event;var _mouseCurrentLocation={x:evt.screenX,y:evt.screenY};_dragObjCurrentLocation.x=_dragObjCurrentLocation.x+(_mouseCurrentLocation.x- _mouseLastLocation.x);_dragObjCurrentLocation.y=_dragObjCurrentLocation.y+(_mouseCurrentLocation.y- _mouseLastLocation.y);_mouseLastLocation=_mouseCurrentLocation;$(_dragObj).css("left",_dragObjCurrentLocation.x+"px");$(_dragObj).css("top",_dragObjCurrentLocation.y+"px");if(evt.preventDefault)
evt.preventDefault();else
evt.returnValue=false;}};var dragMouseUpHandler=function(evt){if(_flag){evt=evt||window.event;$("#jd_dialog_m_b_1").hide();cleanMouseHandlers();_flag=false;}};var cleanMouseHandlers=function(){if(_controlObj){$(_controlObj.document).unbind("mousemove");$(_controlObj.document).unbind("mouseup");}};return{Register:function(dragObj,controlObj){_dragObj=dragObj;_controlObj=controlObj;$(_controlObj).bind("mousedown",dragMouseDownHandler);}}}();