package com.caihong.cms.entity.main;

import java.io.Serializable;
import java.util.Date;

import com.caihong.core.entity.CmsUser;

/**
 * Model class of 排班表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Schedule implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** 医生 */
	private CmsUser doctor;

	/** 资源日期. */
	private Date scheduleTime;

	/** 资源价格. */
	private Double price;

	/** 可用数量. */
	private Integer counts;

	/** 状态. */
	private Byte status;

	/**
	 * Constructor.
	 */
	public Schedule() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 医生id.
	 * 
	 * @param doctorId
	 *            医生id
	 */
	public void setDoctor(CmsUser doctor) {
		this.doctor = doctor;
	}

	/**
	 * Get the 医生.
	 * 
	 * @return 医生
	 */
	public CmsUser getDoctor() {
		return this.doctor;
	}

	/**
	 * Set the 资源日期.
	 * 
	 * @param scheduleTime
	 *            资源日期
	 */
	public void setScheduleTime(Date scheduleTime) {
		this.scheduleTime = scheduleTime;
	}

	/**
	 * Get the 资源日期.
	 * 
	 * @return 资源日期
	 */
	public Date getScheduleTime() {
		return this.scheduleTime;
	}

	/**
	 * Set the 资源价格.
	 * 
	 * @param price
	 *            资源价格
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * Get the 资源价格.
	 * 
	 * @return 资源价格
	 */
	public Double getPrice() {
		return this.price;
	}

	/**
	 * Set the 可用数量.
	 * 
	 * @param counts
	 *            可用数量
	 */
	public void setCounts(Integer counts) {
		this.counts = counts;
	}

	/**
	 * Get the 可用数量.
	 * 
	 * @return 可用数量
	 */
	public Integer getCounts() {
		return this.counts;
	}

	/**
	 * Set the 状态.
	 * 
	 * @param status
	 *            状态
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * Get the 状态.
	 * 
	 * @return 状态
	 */
	public Byte getStatus() {
		return this.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Schedule other = (Schedule) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
