package com.caihong.cms.entity.main;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * Model class of 医生排班.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserSchedule implements Serializable {
	public final static Map<String,String> map=new HashMap<String,String>();
	static{
		map.put("0", "周一");
		map.put("1", "周二");
		map.put("2", "周三");
		map.put("3", "周四");
		map.put("4", "周五");
		map.put("5", "周六");
		map.put("6", "周日");
		
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_id. */
	private Integer id;

	/** 看诊状态. */
	private String zuozhenTimes;
	
	private String sign;	

	/** 可看诊次数. */
	private Integer counts;

	/** 开始日期. */
	private Date startDate;

	/** 结束时间. */
	private Date endDate;

	/** 坐诊价格. */
	private Double price;

	/** 创建时间. */
	private Date createTime;
	
	// one to one
	private com.caihong.core.entity.CmsUser user;

	/**
	 * Constructor.
	 */
	public UserSchedule() {
	}
	
	public static void main(String args[]){
		System.out.println(map.get("1"));
	}
	
	public String getZuozhen(){
		String out="";
		if(this.getZuozhenTimes()!=null){
			
			String arr[]=getZuozhenTimes().split(",");
			for(int i=0;i<arr.length;i++){
				if(arr[i].equals("1")){
					out=out+map.get(""+i)+",";
				}else{
					continue;
				}
			}
		}
		return out;
	}

	/**
	 * Set the user_id.
	 * 
	 * @param userId
	 *            user_id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the user_id.
	 * 
	 * @return user_id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 看诊状态.
	 * 
	 * @param zuozhenTimes
	 *            看诊状态
	 */
	public void setZuozhenTimes(String zuozhenTimes) {
		this.zuozhenTimes = zuozhenTimes;
	}

	/**
	 * Get the 看诊状态.
	 * 
	 * @return 看诊状态
	 */
	public String getZuozhenTimes() {
		return this.zuozhenTimes;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * Set the 可看诊次数.
	 * 
	 * @param counts
	 *            可看诊次数
	 */
	public void setCounts(Integer counts) {
		this.counts = counts;
	}

	/**
	 * Get the 可看诊次数.
	 * 
	 * @return 可看诊次数
	 */
	public Integer getCounts() {
		return this.counts;
	}

	/**
	 * Set the 开始日期.
	 * 
	 * @param startDate
	 *            开始日期
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Get the 开始日期.
	 * 
	 * @return 开始日期
	 */
	public Date getStartDate() {
		return this.startDate;
	}

	/**
	 * Set the 结束时间.
	 * 
	 * @param endDate
	 *            结束时间
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the 结束时间.
	 * 
	 * @return 结束时间
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the 坐诊价格.
	 * 
	 * @param price
	 *            坐诊价格
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * Get the 坐诊价格.
	 * 
	 * @return 坐诊价格
	 */
	public Double getPrice() {
		return this.price;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserSchedule other = (UserSchedule) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public com.caihong.core.entity.CmsUser getUser() {
		return user;
	}

	public void setUser(com.caihong.core.entity.CmsUser user) {
		this.user = user;
	}

}
